spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:jwt_security
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

application:
  security:
    jwt:
      secret-key: Amen
      expiration: 3600000
      refresh-token:
        expiration: 7200000
server:
  port: 8081
